const logger = require('./logger')
const service = require('./service')
logger.log("hello1")
logger.log("hello1")
logger.log("hello1")
logger.log("hello1")
service.action("hello1")
service.action("hello1")
service.action("hello1")
service.action("hello1")
service.action("hello1")
